Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

urlpatterns += staticfiles_urlpatterns()

pizzas/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length = 100)

    def __str__(self):
        return self.pizza_name

class Toppings(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    topping_name = models.CharField(max_length = 100)

    class Meta:
        verbose_name_plural = 'Toppings'

    def __str__(self):
        return self.topping_name

pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Toppings
# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()


    context = {'pizzas': pizzas}


    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    ## view must be consistent with url
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.order_by('-topping_name')

    context = {'pizza': pizza, 'toppings': toppings}

    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Brady's Pizzeria</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body>

        <!-- Static navbar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'pizzas:index' %}">
                        Brady's Pizzeria</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'pizzas:pizzas' %}">Pizzas</a></li>
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>

        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>

        </div> <!-- /container -->

    </body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Check our our pizzas! Go to the dropdown menu to preview our delicious pizzas.</h1>
    </div>
{% endblock header %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block header %}
    <h2>{{ pizza }} Pizza - check out our awesome toppings!</h2>
{% endblock header %}

{% block content %}
    {% for topping in toppings %}
        <div class="panel panel-default">
            <div class="panel-body">
               {{ topping.topping_name|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% endfor %}
    <p>
        {% load static %} <img src="{% static 'pizzas/media/' %}{{pizza}}.jpg"  alt= {{ pizza }} />
    </p>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block header %}
    <h1>Pizzas</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for pizza in pizzas %}
            <li>
                <h3>
                    <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
                </h3>
            </li>
        {% endfor %}
    </ul>

    {% endblock content %}